# -*- coding: utf-8 -*-
"""cnn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AtYSKSwPJjzOuxn5lwzyZH_a3jWFEW1D
"""

from keras.datasets import cifar10
import matplotlib.pyplot as plt

(x_train,y_train),(x_test,y_test)=cifar10.load_data()

x_train.shape

x_test.shape

x_train=x_train.reshape(50000,32,32,3).astype('float64')
x_test=x_test.reshape(10000,32,32,3).astype('float64')

x_train/=255
x_test/=255

from keras.models import Sequential
from keras.layers import Conv2D,MaxPool2D,Flatten,Dense

cnn=Sequential()
cnn.add(Conv2D(32,kernel_size=(3,3),activation='relu',input_shape=(32,32,3)))

cnn.add(MaxPool2D((2,2)))

cnn.add(Conv2D(32,activation='relu',kernel_size=(3,3)))

cnn.add(MaxPool2D((2,2)))

cnn.add(Flatten())

cnn.add(Dense(64,activation='sigmoid'))

cnn.add(Dense(10,activation='softmax'))

cnn.summary()

cnn.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

cnn.fit(x_train,y_train,epochs=20)

re=cnn.evaluate(x_test,y_test)
re

import matplotlib.pyplot as plt

plt.figure(figsize=(5,2))
plt.imshow(x_train[0])