# -*- coding: utf-8 -*-
"""decisiontreefinal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14hSkGpjpM6POryE8Ag6ZY4MOqW4q7pcS
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

data=load_iris()

data

x=data.data
y=data.target

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=50)

c1=DecisionTreeClassifier(criterion="gini")
c1.fit(xtrain,ytrain)

pred=c1.predict(xtest)

print("train accuracy",accuracy_score(ytrain,c1.predict(xtrain)))

print("test accuracy",accuracy_score(ytest,pred))

from sklearn.tree import export_graphviz
from six import StringIO
from IPython.display import Image
import pydotplus
dot_data=StringIO()
export_graphviz(c1,out_file=dot_data,filled=True,rounded=True,special_characters=True,
                feature_names=data.feature_names,class_names=data.target_names)
graph=pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())

cl2=DecisionTreeClassifier(criterion="entropy")
cl2.fit(xtrain,ytrain)
pred=cl2.predict(xtest)

dot_data=StringIO()
export_graphviz(cl2,out_file=dot_data,filled="True",rounded="True",special_characters="True"
,feature_names=data.feature_names,class_names=data.target_names)
graph=pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())

print('train accuracy',accuracy_score(ytrain,cl2.predict(xtrain)))
print("test accuracy",accuracy_score(ytest,pred))

