# -*- coding: utf-8 -*-
"""kmeans2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qd1xLeSS62U4UKYtlj-M0R5oort__Y_O
"""

import pandas as pd

ds=pd.read_csv('ds/College_Data')

ds

ds=ds.drop('Unnamed: 0',axis=1)

ds

from sklearn.cluster import KMeans

km=KMeans(n_clusters=2)

km.fit(ds.drop('Private',axis=1))

km.labels_

km.cluster_centers_

def conv(k):
    if k=='Yes':
        return 1
    else:
        return 0

ds['cluster']=ds['Private'].apply(conv)

ds

from sklearn.metrics import accuracy_score

accuracy_score(ds['cluster'],km.labels_)

