# -*- coding: utf-8 -*-
"""multipleRegerssion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EiDQo86ca9YujTbjIPq-T2Tvn9ZIbNbj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/USA_Housing.csv')

df.head()

df.drop(columns='Address',inplace=True)
df

x=df.drop('Price',axis=1)
y=df['Price']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

mr=LinearRegression()

mr.fit(x_train,y_train)

pred=mr.predict(x_test)

from sklearn.metrics import r2_score
print(r2_score(y_test,pred))

plt.scatter(y_test,pred)
plt.xlabel('actual')
plt.ylabel('predicted')

new=pd.DataFrame({'actual':y_test,'predict':pred})
new