# -*- coding: utf-8 -*-
"""regresion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R-9SA70XYu4kkS8Cs_kYToElo5XQCNY9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Salary_Data.csv')

dataset

x=dataset[['YearsExperience']]
y=dataset[['Salary']]

x

y

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

lr=LinearRegression()

lr.fit(x_train,y_train)

pred=lr.predict(x_test)

print(mean_squared_error(y_test,pred))

plt.scatter(x_train,y_train,color='red')
plt.plot(x_train,lr.predict(x_train),color='blue')

plt.scatter(x_test,y_test,color='red')
plt.plot(x_test,pred,color='blue')

"""Mutiple LinearRegression"""

