# -*- coding: utf-8 -*-
"""SVM___.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EobF7YlFAU1FpZW7pk1L2u7tAzi5v8hE
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import SVC
from nltk.corpus import stopwords
import string

# Load the SMS Spam Collection dataset
ds = pd.read_csv('ds/Spam.csv')

ds

def conv(k):
    if k=='spam':
        return 1
    else:
        return 0

ds['Category']=ds['Category'].apply(conv)

ds

def preprocess(mess):
    mess=[c for c in mess if c not in string.punctuation]
    nopunc="".join(mess)
    clean=" ".join([c for c in nopunc.split() if c.lower() not in stopwords.words('english')])
    return clean.lower()
ds['Message']=ds['Message'].apply(preprocess)

ds

xtr,xt,ytr,yt=train_test_split(ds['Message'],ds['Category'],random_state=42)

vec=CountVectorizer()

vec_xtr=vec.fit_transform(xtr)

vec_xt=vec.transform(xt)

smod=SVC()

smod.fit(vec_xtr,ytr)

pred=smod.predict(vec_xt)

from sklearn.metrics import accuracy_score

accuracy_score(pred,yt)

msg=["Free entry in 2 a wkly comp to win Primiel Ligue"]
vec_msg=vec.transform(msg)

smod.predict(vec_msg)

